// // *********
// // *********
// // *********
// // *********

#include<iostream>
using namespace std;


int main(){
int n,m;
cout<<"enter the no. of n"<<endl;
cout<<"enter the no. of m";
cin>>n>>m;
for(int i =0;i<=5;i++){
    for(int j = 0;j<=m;j++){
        cout<<"*";
    }
} 
}
// 
// #include <iostream>
// using namespace std;

// int main() {
//     // Number of rows
//     int rows = 4;
//     // Number of stars in each row
//     int stars = 9;

//     for (int i = 0; i < rows; i++) {
//         for (int j = 0; j < stars; j++) {
//             cout << "*";
//         }
//         cout << endl; // Move to next line
//     }

//     return 0;
// }
